### ISSUE TITLE
cloneDeep no cloning methods?

### ISSUE THREAD

**Issue by SeeThruHead** [toss/es-toolkit#777] opened 2024-10-31 14:11 UTC
i was trying to get rid of cloneDeep from lodash in our app today and ran into the issue of many methods being undefined on some models we have

just wanted to check to make sure that is expected behaviour of cloneDeep 

thanks

**Comment by raon0211** [comment] 2024-11-01 02:06
Hello :) Does the problem also occur for `cloneDeep` in our compatibility library? 

```tsx
import { cloneDeep } from 'es-toolkit/compat';
```

For `cloneDeep` in our original library, let us check this.

**Comment by SeeThruHead** [comment] 2024-11-01 02:30
hello
i just started on a new codebase that is using cloneDeep to clone instantiated classes all over

switching to `import { cloneDeep } from 'es-toolkit'` causes our test to fail with missing methods
i just tried to use es-toolkit/compat and have the same issues

i moved us from lodash to lodash-es to reduce the bundle size and neither of those give us issues with cloneDeep-ing our classes

**Comment by filipsobol** [comment] 2024-11-05 09:26
I encountered the same issue. Here's a minimal reproduction comparing the behavior in `lodash-es`, `es-toolkit`, and `es-toolkit/compat`: https://stackblitz.com/edit/stackblitz-starters-eanrtc?file=index.js.

It looks like class instances are turned into plain objects.

**Comment by filipsobol** [comment] 2024-11-05 17:45
Fixed in https://github.com/toss/es-toolkit/pull/794

**Comment by raon0211** [comment] 2024-11-10 12:30
This was fixed in es-toolkit v1.27.0 :)

**Closed by raon0211** 2024-11-10 12:30 UTC
